export enum ColorTheme {
  BACKGROUND_DARK = 'background_dark',
  BACKGROUND_LIGHT = 'background_light',
  BACKGROUND_NORMAL = 'background_normal',
  ERROR_DARK = 'error_dark',
  ERROR_LIGHT = 'error_light',
  ERROR_NORMAL = 'error_normal',
  PRIMARY_DARK = 'primary_dark',
  PRIMARY_LIGHT = 'primary_light',
  PRIMARY_NORMAL = 'primary_normal',
  SECONDARY_DARK = 'seconday_dark',
  SECONDARY_LIGHT = 'seconday_light',
  SECONDARY_NORMAL = 'seconday_normal',
  SUCCESS_DARK = 'success_dark',
  SUCCESS_LIGHT = 'success_light',
  SUCCESS_NORMAL = 'success_normal',
  SURFACE_DARK = 'surface_dark',
  SURFACE_LIGHT = 'surface_light',
  SURFACE_NORMAL = 'surface_normal',
  WARNING_DARK = 'warning_dark',
  WARNING_LIGHT = 'warning_light',
  WARNING_NORMAL = 'warning_normal',
}
